# - name: configure k8s
#   hosts: kube-cluster
#   become: yes
#   roles:
#   - configure-k8s


# # instaling container 

# - name: install container runtime
#   hosts: kube-cluster
#   become: yes
#   roles:
#   - docker


# - hosts: master
#   gather_facts: yes
#   become: yes
#   roles:
#   - {role: kubernetes/master, tags: master}
#   - {role: cni, tags: cni,}

# - hosts: node
#   gather_facts: yes
#   become: yes
#   roles:
#   - {role: kubernetes/node, tags: node,}

- hosts: master
  gather_facts: yes
  become: yes
  tasks:
  - name: "Helm role"
    include_role:
      name: helm
    when: "additional_features.helm"
    run_once: yes
    tags: helm
